### PR TITLE
feat: Adding husky as precommit hook

### PR DESCRIPTION
**Pull request by shravan20**
Description:

This PR deals with adding and setting up husky as the pre-commit hook. I will add the FE and BE linter and then include them as part of the pre-commit hooks.

### CODE REVIEW

**Comment by shravan20** [comment]
@idodav: This is good for review, thanks! :D

**Comment by idodav** [comment]
Please fix the conflict

**Comment by shravan20** [comment]
> Please fix the conflict

@idodav: Conflicts has been resolved

**Review by idodav — APPROVED** [review]

**Comment by idodav** [comment]
Awesome thank you very much :) 
Approved and merged
@shravan20

**Pull request merged**
