### PR TITLE
Feature/winston logger

### PR DESCRIPTION
**Pull request by nkotzrenko**
* Added a dependency on winston in the backend system
* Changed all references from console.* to log.* accordingly
* Created a general log with specific additional data per each file using the [winston].child method

For now the only transport we work with is console alongside formats of timestamp and json - it should be enough for the time being.

### CODE REVIEW

**Review by idodav — APPROVED** [review]

**Comment by SID262000** [comment]
@idodav It's really important to pay emphasis to the documentation of the codebase. Looks like the documentation is missing from the changes made, this shall make it difficult to onboard any additional developer.
I would like to request @nkotzrenko to please look into this and improvise the codebase.

**Comment by SID262000** [comment]
Also, @nkotzrenko can you please confirm in case the above changes have been run through the associated linters, Thanks
cc: @idodav

**Comment by nkotzrenko** [comment]
> @idodav It's really important to pay emphasis to the documentation of the codebase. Looks like the documentation is missing from the changes made, this shall make it difficult to onboard any additional developer. I would like to request @nkotzrenko to please look into this and improvise the codebase.

Hi @SID262000, I'd like to ask; What do you mean by documentation of the changes made? (Other than the changes written in the PR in bulletin points)

Also, what do you mean exactly by improvise the codebase? What do you exactly propose to be done in the codebase? Adding an on-boarding document? A changes document when a version is released?

Thank you in advance,

**Comment by SID262000** [comment]
Hi @nkotzrenko ,

It's always important to have a well documented codebase, couple of specific points like adhering to 5 lines of code, adding comments, following SOLID Principles wherever applicable. Although the caveat here is it might lead to over engineering at times.

**Comment by idodav** [comment]
@SID262000 I don't really like the 5 lines of code rule. Also, I don't really like comments. Only when necessary. The Code should explain itself. 
As for documentation. Do you have any practical example/suggestion?

**Comment by SID262000** [comment]
@idodav For Reference: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

**Pull request merged**
